#!/bin/bash

# build-remote-debian-installer
# 
# Grabs the stable installer from git or apt
# and configures it to allow installation via
# SSH remotely.

source common.sh

if [[ $UID != 0 ]]; then
  info 'This script needs root privileges to run, trying sudo'
  sudo echo || exit 1
fi

info 'Installing dependencies for chroot'
sudo aptitude install binutils debootstrap

info 'Creating chroot for build'
sudo /usr/sbin/debootstrap --arch "$ARCH" wheezy di-chroot http://cdn.debian.net/debian
sudo mkdir -p di-chroot/opt/di-build
sudo cp common.sh chroot-payload di-chroot/opt/di-build/

info 'Entering chroot...'
sudo /usr/sbin/chroot di-chroot /opt/di-build/chroot-payload
